### ISSUE TITLE
Package cannot be uninstalled

### ISSUE THREAD

**Issue by Erftralle** [JoomGalleryfriends/JoomFinderPlugin#1]
When trying to uninstall the package one gets the warning:

**_Trying to uninstall unknown extension from package. This extension may have already been removed earlier._**

Both plugins are still installed after trying to remove the package.

**Comment by Elfangor93** [comment]
Issue fixed with commit 887f756

**Comment by Erftralle** [comment]
Confirmed that issue has been fixed. Thank you.
