### ISSUE TITLE
Images are still indexed when deleting a complete category in category manager containing images

### ISSUE THREAD

**Issue by Erftralle** [JoomGalleryfriends/JoomFinderPlugin#5]
If one deletes a complete category in category manager containing images the images seem still to be indexed. One gets the message: Warning: Trying to access array offset on value of type null in ...\components\com_joomgallery\router.php on line 329

**Comment by Elfangor93** [comment]
Issue should be fixed with the commit 820c25e

**Comment by Erftralle** [comment]
Confirmed that issue has been fixed. Thank you.
